### PR TITLE
Code review request - Add test on gene page

### PR DESCRIPTION
**Pull request by Withington**
This is a code review request, not a merge request at this stage.

Added test on gene page. Load data from file in to dbs named as 'test_xx'. Added names of hpo and patient dbs to config. WIP - started to change code to get db names from app.config.

I’ve added a test that the TTLL5 gene page loads up ok. To do this, it needs data. I considered three options below and went with option 2 - 
1.	**Add mock db** (this makes the unittests self-contained but introduces more complexity. Plus, the tests already use mongo for the login and it works fine in Travis-CI)
2.	**Add data to mongo whilst running the test.** (this duplicates some code from easy_install.sh but doesn’t add additional external dependencies)
3.	**Add mongo data imports to a test script**. (the unittests would become less self-contained).

Any differing opinions or options?

•	Is there any danger that running the tests in the Prod env could end up writing data to the Prod db?
•	I had to import the data slightly differently from easy_install, do you think this could make testing some aspects of phenopolis difficult in the future? Differences -
o	Added json.loads(line.replace("$oid", "ObjectId").replace("$numberLong", "NumberLong")) 
o	It’s unable to create an ‘EXAC’ index on uclex-variant-TTLL5.json, error – key too long. Any ideas?
•	Loading the data takes about 1min, is there any data that won’t be needed for tests?

**To do –** 
•	Add more checks to the final set of asserts. Any ideas on how to check that the circles diagram is present?
•	Change ALL usage of get_db(..) and of db names to get db names from config, e.g. hpo_db=get_db(app.config['DB_NAME_HPO'])
•	Only import data once per test file, i.e. load_data() to check to see if data has already been loaded.
•	Add a common test helper function to login, logout.

### CODE REVIEW

**Comment by pontikos** [comment]
Hi Lucy,

Thanks for this.

Added test on gene page. Load data from file in to dbs named as 'test_xx'.
> Added names of hpo and patient dbs to config. WIP - started to change code
> to get db names from app.config.
>
Yes I think this is a good idea to have these files in the repository
rather than have to download them each time:
https://github.com/pontikos/phenopolis/tree/master/tests/data


> I’ve added a test that the TTLL5 gene page loads up ok. To do this, it
> needs data. I considered three options below and went with option 2 -
>
>    1. *Add mock db* (this makes the unittests self-contained but
>    introduces more complexity. Plus, the tests already use mongo for the login
>    and it works fine in Travis-CI)
>
>
>    1. *Add data to mongo whilst running the test.* (this duplicates some
>    code from easy_install.sh but doesn’t add additional external dependencies)
>
>
>    1. *Add mongo data imports to a test script*. (the unittests would
>    become less self-contained).
>
> Yes I think loading the data as part of the test script is the best option
but perhaps you are right that for the local.cfg we should specify a
different database so as to not accidentally overwrite the live database if
run on the server.

>
>
> Any differing opinions or options?
>
> • Is there any danger that running the tests in the Prod env could end up
> writing data to the Prod db?
>
Yes, we should use different db names, specified in local.cfg, to make sure
this doesn't happen.

> • I had to import the data slightly differently from easy_install, do you
> think this could make testing some aspects of phenopolis difficult in the
> future? Differences -
> o Added json.loads(line.replace("$oid", "ObjectId").replace("$numberLong",
> "NumberLong"))
> o It’s unable to create an ‘EXAC’ index on uclex-variant-TTLL5.json, error
> – key too long. Any ideas?
>
 Ok I'll have a look.

> • Loading the data takes about 1min, is there any data that won’t be
> needed for tests?
>
I think we need to load all the data.


> *To do –*
> • Add more checks to the final set of asserts. Any ideas on how to check
> that the circles diagram is present?
>
Do you mean the Phenogenon diagram?  I think we could use some web testing
framework.
https://wiki.python.org/moin/PythonTestingToolsTaxonomy#Web_Testing_Tools


> • Change ALL usage of get_db(..) and of db names to get db names from
> config, e.g. hpo_db=get_db(app.config['DB_NAME_HPO'])
>
Yes I think that's a great idea, we should move all hardcoded strings
(database names etc) to the config file.

> • Only import data once per test file, i.e. load_data() to check to see if
> data has already been loaded.
>
Yes.

> • Add a common test helper function to login, logout.
>
Yes that would be good.

Thanks,

Nikolas.

**Comment by Withington** [comment]
Good idea to use tests/data to get the data for easy_install too, thanks.

**Comment by Withington** [comment]
On checking that the Phenogenon diagram is rendered, are there any checks that can be done from the unit test, rather than having to use a web testing tool? E.g. I already check that the text "Macular dystrophy" appears on the page (or at least in the returned data from render_template()). Can you think of anything I could check for that would verify that the diagram has been created?

Alternatively - how could I prevent the diagram from being rendered? Then I can look at the difference in the data returned by render_template().

**Comment by pontikos** [comment]
I think we could check that the json on the webpage is valid?

**Comment by Withington** [comment]
Tell me more? Where in the code can I get hold of the json? Is that json related to the diagram only, not other aspects of the webpage?

**Comment by IsmailM** [comment]
Hey

From what I understand, the SVG diagrams on the gene page are generated using the following python variables which are embedded into the page when the server renders the page.

```
hpo_terms_json
patients_status
dot_hom_comp
dot_het
```

> RANT (ignore this bit ;) ) - this is usually bad practice for so many reasons; most importantly due to security and speed reasons. Rather it should be implemented as an AJAX call where the web page provides its session id and asks the server for this as a formatted JSON...

Thus to answer your question to test the JSON, simply test those variables....


Secondly, the SVG is generated after the page is fully loaded via Javascript on the clientside and as such you will not be able to see it in `self.app.get('/gene/TTLL5').data`, which I understand only returns the rendered HTML. In order to see the SVG, you will need to use something like PhantomJS, etc. which would update the HTML DOM using JS which you can then access...

A quick and important test for all the pages would be to check the return status code e.g.:

```
pwd = dict(username='demo123', password='demo123')
self.app.post('/login', data=pwd, follow_redirects=True)
page = self.app.get('/gene/TTLL5', follow_redirects=True)
assertEqual(page.status_code, 200)
``` 

This should typically be 200 ( which means successful connection) ... Other common statuses include 404 and 500. See [wikipidea for more info](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).

This could be run on each endpoint...


On a side note, I'm currently re-designing the frontend from the bottom up (with a focus on user interface/ experience) - I'm redoing the HTML/CSS from scratch and heavily rewriting/ refactoring the javascript. I'm currently 10% of the way through and am aiming to finish that within the next 2.5 weeks.

As such I would suggest that we leave testing the frontend (i.e. testing presence of a DOM element etc.) until after that to avoid doing it all over when the frontend's code base changes significantly. I would be happy to help with developing a proper frontend test e.g. with selenium (which uses PhantomJs) etc.

Another useful way of testing the front-end is using a spider framework which could be used to verify status codes and also run HTMLtidy to ensure properly formatted HTML.

**Comment by Withington** [comment]
Thanks Ismail.

Yes, I'm more interested at this stage in testing that the information underlying the diagram is correct than checking that it renders correctly. I'd like to do as much as is practical in the unit tests, to minimise the load on any web testing. If I've understood you correctly, I _could_ test the data in hpo_terms_json, etc. but it's best not to as you are changing things in that area. Instead, I'll go ahead and add the quick test on the status code that you suggest.

BTW if you are choosing a web test tools, it would be advantageous if it is one that can be run under Travis-CI (such as Selenium, as you mention).

**Comment by pontikos** [comment]
Hi Ismail,

> On a side note, I'm currently re-designing the frontend from the bottom up
> (with a focus on user interphase/ experience) - I'm redoing the HTML/CSS
> from scratch and heavily rewriting/ refactoring the javascript. I'm
> currently 10% of the way through and am aiming to finish that within the
> next 2.5 weeks.
>
Fantastic! Looking forward to seeing this!

> As such I would suggest that we leave testing the frontend (i.e. testing
> presence of a DOM element etc.) until after that to avoid doing it all over
> when the frontend's code base changes significantly. I would be happy to
> help with developing a proper frontend test e.g. with selenium (which uses
> PhantomJs) etc.
>
Yes I agree with you and Lucy, right now we are more interested in the
content rather than the rendering.
Let's wait for you to finish the UI rehaul before testing the rendering.

> Another useful way of testing the front-end is using a spider framework
> which could be used to verify status codes and also run HTMLtidy to ensure
> properly formatted HTML.
>

Many Thanks!

Nikolas.

**Pull request merged**
