### PR TITLE
removed dependency on BioTools

### PR DESCRIPTION
**Pull request by logust79**
- removed dependency on BioTools
- added `gene_names_to_ids` to `offline_analysis/commons/phenopolis_utils.py`, where it can translate gene symbols or alias or old names to ensembl ids
- `get_candidate_genes` now use `gene_names_to_ids` for translation

### CODE REVIEW

**Comment by pontikos** [comment]
@logust79 some tests failed

**Comment by logust79** [comment]
@pontikos guess coveralls didn't like it. Travis didn't complain anything

**Comment by pontikos** [comment]
Hi @logust79 can you find out what checks are failing please and fix it so I can merge this PR?

**Comment by logust79** [comment]
so far as I know no checks fail. It complains because the coverage decreases

**Pull request merged**
