### PR TITLE
update publication links

### PR DESCRIPTION
**Pull request by IsmailM**

### CODE REVIEW

**Comment by Withington** [comment]
How about using this link instead - https://doi.org/10.1093/bioinformatics/btx147 ?
From doi.org - "Clicking on a DOI link takes you to one or more current URLs or other services related to a single resource. If the URLs or services change over time, e.g., the resource moves, this same DOI will continue to resolve to the correct resources or services at their new locations."

**Comment by IsmailM** [comment]
Thanks - Have fixed...

@Withington - can you take a look a merge when u r happy with it 👍

**Comment by Withington** [comment]
@IsmailM there is one more, in phenopolis\templates\terms.html

**Comment by IsmailM** [comment]
I don't think that's a Phenopolis publication... :)

(The terms page is old - and is reminiscent of the Exac Project project; from which this project was forked)...

**Comment by Withington** [comment]
Ah yes I see now :)

**Pull request merged**
